In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv ('Downloads/AfroFinChain_Multilingual_Web3_QA_EN_YO_PCM_HA_IG.csv')
df.head(5)

,entry_id,term_en,definition_en,category,complexity,en_question,en_answer,ha_question,ha_answer,ig_question,...,ec_en_answer,ec_yo_question,ec_yo_answer,ec_pcm_question,ec_pcm_answer,ec_ha_question,ec_ha_answer,ec_ig_question,ec_ig_answer,ec_source
0,W3AF-001,0x Protocol,An open-source infrastructure that enables the...,Infrastructure,Advanced,Can I use 0x Protocol to swap my coins without...,0x is an open-source infrastructure that enabl...,Zan iya amfani da 0x Protocol don musayar kudi...,Wani tsarin kwamfuta ne wanda ke bawa mutane d...,M̀ nwere ike iji 0x Protocol gbanwere ego m n'...,...,"Yes, you can. 0x Protocol allows you to trade ...",Ṣé mo lè lo 0x Protocol láti ṣe pàṣípàrọ̀ owó ...,"Bẹ́ẹ̀ ni, o lè ṣe é. Ó dàbí bí a ṣe ń ṣe Ajo, ...",I fit use 0x Protocol trade my ETH coins witho...,"Yes, you fit. E be like when you buy recharge ...",Zan iya amfani da 0x Protocol don musayar kudi...,"Kwarai kuwa. Yana kama da tsarin Adashi, inda ...",M̀ nwere ike iji 0x Protocol gbanwere ego m n'...,"Ee, ị nwere ike. Ọ dị ka otu anyị si eme Isusu...",coinmarketcap.com
1,W3AF-002,51% attack,A type of attack where a group gains control o...,Security,Intermediate,Can one group of bad people take over the whol...,A 51% attack occurs when a group gains control...,Shin wasu mugaye za su iya mallakar mafi yawan...,Wani nau'in hari ne inda rukuni ke samun ikon ...,Otu nzukọ ọjọọ nwere ike ịchịkwa ihe karịrị ọk...,...,"Yes, if they control more than half the networ...",Ṣé ẹgbẹ́ kan lè gba ìṣàkóso blockchain láti yí...,"Bẹ́ẹ̀ ni, tí wọ́n bá gba iṣakoso tó ju ìdajì l...",One bad group fit carry more than half of di c...,"Yes, if dem get pass half network power, dem f...",Shin wasu mugaye za su iya mallakar mafi yawan...,"Eh, idan rukuni ya mallaki fiye da rabi, za su...",Otu nzukọ ọjọọ nwere ike ịchịkwa ihe karịrị ọk...,"Ee, ma ọ bụrụ na ha nwere ike ịchịkwa ihe karị...",ethereum.org\n
2,W3AF-003,52-Week High/Low,The highest and lowest market prices of a give...,Analytics,Beginner,How can I know the highest and lowest price a ...,The 52-week high/low represents the highest an...,Ta yaya zan gane mafi girma da mafi kankantar ...,Mafi girma da mafi kankantar farashin jari ne ...,Kedu otu m ga-esi mata ego kacha elu na nke ka...,...,It shows the peak and bottom price for a coin ...,Báwo ni mo ṣe lè mọ iye owó tó ga jù àti èyí t...,Iye owó tó ga jù àti èyí tó kéré jù fún ohun ì...,Wetin be di biggest and smallest price wey dis...,Na di highest and lowest price wey one coin re...,Ta yaya zan gane mafi girma da mafi kankantar ...,Shi ne mafi girma da mafi kankantar farashin j...,Kedu otu m ga-esi mata ego kacha elu na nke ka...,Ọ bụ ọnụahịa kacha elu na nke kacha ala ihe ru...,coinmarketcap.com\n
3,W3AF-004,52-Week Range,The difference between an asset’s highest and ...,Analytics,Beginner,How do I see the lowest and highest price a co...,You check the 52-Week Range; it shows the pric...,Yaya zan iya sanin mafi girma da mafi kankanta...,Za ka duba 52-Week Range; yana nuna mafi girma...,Kedu otu m ga-esi mara ego kacha elu na nke ka...,...,You check the 52-Week Range on any market trac...,Báwo ni mo ṣe lè mọ iye owó tó ga jù àti èyí t...,Wo 52-Week Range; ó ń fi iye owó tó ga jù àti ...,How I go take know di highest and lowest price...,Check 52-Week Range; e show di highest and low...,Yaya zan iya sanin mafi girma da mafi kankanta...,Duba 52-Week Range; yana nuna mafi girma da ma...,Kedu otu m ga-esi mara ego kacha elu na nke ka...,Ị ga-eleba anya na 52-Week Range; ọ bụ ọnụahịa...,coinmarketcap.com
4,W3AF-005,80/20 Rule (Pareto Principle),A principle stating that 20% of actions or par...,Culture,Beginner,Is it true that only a small group of people h...,The Pareto Principle states that 20% of partic...,Shin gaskiya ne wasu mutane kadan ne ke da maf...,Wata ka'ida ce dake cewa kashi 20 na ayyukan m...,Ọ̀ bụ eziokwu na ọ bụ naanị mmadụ ole na ole n...,...,"Yes, this reflects the Pareto Principle where ...",Ṣé òótọ́ ni pé àwọn èèyàn díẹ̀ ló ní iye owó t...,"Bẹ́ẹ̀ ni, ìdá ogún ènìyàn ló máa ń ní ìdá ọgọ́...",Na true say only small people for crypto get a...,"True o, e be like how one person fit hold all ...",Shin gaskiya ne wasu mutane kadan ne ke da maf...,"Haka ne, kamar yadda wasu kalilan suke da mafi...",Ọ̀ bụ eziokwu na ọ bụ naanị mmadụ ole na ole n...,"Ọ bụ eziokwu, ọ dịka otu onye nwere ego kacha ...",coinmarketcap.com\n

In [7]:
# Bringing out the needed columns from the dataset

df = df[['entry_id','en_question','ha_question','ig_question','yo_question']]
df.head()

,entry_id,en_question,ha_question,ig_question,yo_question
0,W3AF-001,Can I use 0x Protocol to swap my coins without...,Zan iya amfani da 0x Protocol don musayar kudi...,M̀ nwere ike iji 0x Protocol gbanwere ego m n'...,Ṣé mo lè lo 0x Protocol láti ṣe pàṣípàrọ̀ owó ...
1,W3AF-002,Can one group of bad people take over the whol...,Shin wasu mugaye za su iya mallakar mafi yawan...,Otu nzukọ ọjọọ nwere ike ịchịkwa ihe karịrị ọk...,Ṣé ẹgbẹ́ kan lè gba ìṣàkóso blockchain láti yí...
2,W3AF-003,How can I know the highest and lowest price a ...,Ta yaya zan gane mafi girma da mafi kankantar ...,Kedu otu m ga-esi mata ego kacha elu na nke ka...,Báwo ni mo ṣe lè mọ iye owó tó ga jù àti èyí t...
3,W3AF-004,How do I see the lowest and highest price a co...,Yaya zan iya sanin mafi girma da mafi kankanta...,Kedu otu m ga-esi mara ego kacha elu na nke ka...,Báwo ni mo ṣe lè mọ iye owó tó ga jù àti èyí t...
4,W3AF-005,Is it true that only a small group of people h...,Shin gaskiya ne wasu mutane kadan ne ke da maf...,Ọ̀ bụ eziokwu na ọ bụ naanị mmadụ ole na ole n...,Ṣé òótọ́ ni pé àwọn èèyàn díẹ̀ ló ní iye owó t...

In [8]:
# Renaming our columns to make it easier to access and call

df.rename(columns={'entry_id':'Entry_id',
                          'en_question':'English',
                          'ha_question':'Hausa',
                          'ig_question':'Igbo',
                          'yo_question':'Yoruba'
                         }, inplace=True)

df.columns

Index(['Entry_id', 'English', 'Hausa', 'Igbo', 'Yoruba'], dtype='str')

In [9]:
# converting our data to standard format for text classification

records = []
for _, row in df.iterrows():
    records.append([row['English'],'English'])
    records.append([row['Hausa'],'Hausa'])
    records.append([row['Igbo'],'Igbo'])
    records.append([row['Yoruba'],'Yoruba'])

language_df= pd.DataFrame(records,columns=['text','language'])
language_df.head()

                                                text language
0  Can I use 0x Protocol to swap my coins without...  English
1  Zan iya amfani da 0x Protocol don musayar kudi...    Hausa
2  M̀ nwere ike iji 0x Protocol gbanwere ego m n'...     Igbo
3  Ṣé mo lè lo 0x Protocol láti ṣe pàṣípàrọ̀ owó ...   Yoruba
4  Can one group of bad people take over the whol...  English